# Use an official Node runtime as a parent image
FROM node:14-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY frontend/package*.json ./

# Install frontend dependencies
RUN npm install

# Copy the rest of the frontend code
COPY frontend/ .

# Build the React app
RUN npm run build

# Expose port 3000 to the Docker host
EXPOSE 3000

# Command to run the frontend server
CMD ["npm", "start"]
