version: '3'

services:

    backend:
        build:
            context: ./backend
            dockerfile: DockerFile
        
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: trabajofingrado
            DB_USERNAME: root
            DB_PASSWORD:
        
        ports: 
            - 8000:8000
        
        volumes:
            - .backend:/app/backend

        depends_on:
            - db

        networks:
            - app
        

    frontend:
        build:
            context: ./frontend
            dockerfile: dockerfile
        
        environment:
            - VITE_API_URL=${VITE_API_URL}
             
        
        ports:
            - 3000:3000
        
        volumes:
            - ./frontend./app/frontend
        
        depends_on:
            - backend

        networks:
            - app

    
    db:
        image: mysql:5.2.0
        restart: always

        environment:
            MYSQL_DATABASE: 'trabajofingrado'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: ''
            MYSQL_ROOT_PASSWORD: ''

        ports:
          - "3306:3306"
        networks:
            - app


networks:
    app:
        driver: bridge

      