version: '3.9'

services:

    backend:
        build:
            context: ./backend
            dockerfile: dockerfile
        
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: trabajofingrado
            DB_USERNAME: 'cris'
            DB_PASSWORD: 'cris'
        
        ports: 
            - 8000:8000
        
        volumes:
            - .backend:/app/backend

        depends_on:
            - db

        networks:
            - mynetwork
        

    frontend:
        build:
            context: ./frontend
            dockerfile: dockerfile
                
        ports:
            - "5173:5173"

        environment:
            - NODE_ENV=production
        
        networks:
            - mynetwork

    db:
        image: mysql
        restart: always
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_DATABASE: 'trabajofingrado'
            MYSQL_USER: 'cris'
            MYSQL_PASSWORD: 'cris'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        ports:
          - "3306:3306"
        networks:
            - mynetwork

networks:
    mynetwork:
        driver: bridge

      