FROM php:8.2.0-apache


# Set the working directory in the container
WORKDIR /var/www/html

COPY . .


# Copy composer.lock and composer.json
COPY composer.lock composer.json ./

# Install PHP dependencies
RUN apt-get update && apt-get install -y \
    git \
    zip \
    unzip \
    && docker-php-ext-install pdo pdo_mysql

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install Symfony CLI
RUN curl -sS https://get.symfony.com/cli/installer -o /tmp/installer.sh 

RUN bash /tmp/installer.sh

RUN mv /root/.symfony*/bin/symfony /usr/local/bin/symfony

# Expose port 80 to the Docker host
EXPOSE 80

RUN composer install --no-interaction --prefer-dist --optimize-autoloader

# Run Apache server
CMD ["symfony", "server:start", "--no-tls", "--dir=/var/www/html"]
