FROM php:8.2.0-fpm

WORKDIR /var/www/html

COPY ./backend /var/www/html

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libzip-dev \
    && docker-php-ext-install zip pdo_mysql

CMD ["php-fpm"]
